# Generated by Django 5.0.7 on 2024-07-16 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='status',
        ),
    ]
