# Generated by Django 5.0.7 on 2024-07-16 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_content_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['created_date']},
        ),
    ]
