# Generated by Django 5.0.7 on 2024-07-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_content_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='content',
            name='phone',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
