# Generated by Django 5.0.7 on 2024-07-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_w2_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='w2',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
