# Generated by Django 5.0.7 on 2024-07-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_w2_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='w2',
        ),
    ]
