# Generated by Django 5.0.7 on 2024-07-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_delete_w2'),
    ]

    operations = [
        migrations.CreateModel(
            name='w2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title2', models.CharField(blank=True, max_length=255, null=True)),
                ('subject2', models.CharField(max_length=255)),
                ('content2', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
