# Generated by Django 5.0.7 on 2024-07-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_w2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='w2',
            old_name='content2',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='w2',
            old_name='subject2',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='w2',
            old_name='title2',
            new_name='title',
        ),
    ]
