# Generated by Django 5.0.7 on 2024-08-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_w2e_delete_w2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='w1',
            name='content',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='w1',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='w1',
            name='subject',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='w1',
            name='title',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='w2e',
            name='content',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='w2e',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='w2e',
            name='subject',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='w2e',
            name='title',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
