# Generated by Django 5.0.7 on 2024-08-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_w1_content_alter_w1_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='w2e',
            name='content',
            field=models.TextField(blank=True, default='default', null=True),
        ),
    ]
