# Generated by Django 5.0.7 on 2024-08-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_active_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='active',
        ),
    ]
