# Generated by Django 5.0.7 on 2024-08-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_active'),
        ('pythonium', '0014_video_is_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='videos',
            field=models.ManyToManyField(to='pythonium.video'),
        ),
    ]
