# Generated by Django 5.0.7 on 2024-08-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_videos'),
        ('pythonium', '0014_video_is_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, to='pythonium.video'),
        ),
    ]
