# Generated by Django 5.0.7 on 2024-08-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_phone_alter_profile_videos'),
        ('pythonium', '0014_video_is_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='videos',
            field=models.ManyToManyField(to='pythonium.video'),
        ),
    ]
