# Generated by Django 5.0.7 on 2024-08-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_comment_replies_comment_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
