# Generated by Django 5.0.7 on 2024-08-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_cart_cartitem_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
