# Generated by Django 5.0.7 on 2024-07-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonium', '0003_videot_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(null=True, upload_to='deploy/videos/%Y/%m/%d/', verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='videofile',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.ManyToManyField(to='pythonium.videofile'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='VideoT',
        ),
    ]
