# Generated by Django 5.0.7 on 2024-07-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonium', '0006_rename_subject_videofile_discription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
