# Generated by Django 5.0.7 on 2024-07-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonium', '0011_alter_comment_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
