# Generated by Django 5.0.7 on 2024-07-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonium', '0013_video_price_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_product',
            field=models.BooleanField(default=0),
        ),
    ]
